name: CI

env:
  RAILS_ENV: test
  COUCHBASE_CONNECTIN_STRING: ${{ secrets.COUCHBASE_CONNECTION_STRING }}
  COUCHBASE_BUCKET: ${{ secrets.COUCHBASE_BUCKET }}
  COUCHBASE_USER: ${{ secrets.COUCHBASE_USER }}
  COUCHBASE_PASSWORD: ${{ secrets.COUCHBASE_PASSWORD }}
  CI: true

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          COUCHBASE_CONNECTIN_STRING: ${{ secrets.COUCHBASE_CONNECTION_STRING }}
          COUCHBASE_BUCKET: ${{ secrets.COUCHBASE_BUCKET }}
          COUCHBASE_USER: ${{ secrets.COUCHBASE_USER }}
          COUCHBASE_PASSWORD: ${{ secrets.COUCHBASE_PASSWORD }}
          CI: true
        run: |
            gem install bundler
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
            bin/rails spec